import GameType from '@/components/gameType'
import React from 'react'
import Head from 'next/head'

export default function selectGame() {
  return (
    <>
      <Head>
        <title>Tic Tac Toe App Select game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-blackPurple absolute h-full w-full'>
        <div className='md:w-2/3 mx-auto w-full'>
          <div className='py-11 md:px-9 px-6 mb-5'>
            <h1 className='md:text-4xl text-2xl text-lightSecondary border-b-2 border-primary'>Choose Game</h1>
          </div>
          <GameType />
        </div>
      </div>
    </>
  )
}
