import Game from '@/components/game'
import React from 'react'
import Head from 'next/head'

export default function singlePlayer() {
    return (
        <>
            <Head>
                <title>Tic Tac Toe App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='bg-blackPurple absolute h-full w-full'>
                <div className=''>
                    <Game isSinglePlayer={true} isMultiplePlayer={false} player1Name={'You'} singlePlayerTag={'Your'} player1Symbol={'X'} player2Name={'Computer'} player2Symbol={'O'} />
                </div>
            </div>
        </>
    )
}
