import React, { useState } from 'react'
import Head from 'next/head'
import SinglePlayerGame from '@/components/singlePlayerGame'
import PlayersSelect from '@/components/playersSelect';

export default function singlePlayer() {

    const [isUserInfoEntered, setIsUserInfoEntered] = useState(false);
    const [player1Symbol, setPlayer1Symbol] = useState('')
    const [player2Symbol, setPlayer2Symbol] = useState('')
    const [isSinglePlayer, setIsSinglePlayer] = useState('')
    const [singlePlayerTag, setSinglePlayerTag] = useState('')

    return (
        <>
            <Head>
                <title>Tic Tac Toe App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='bg-blackPurple absolute h-full w-full'>
                <div className={`${isUserInfoEntered ? 'pt-8' : 'pt-40'}`}>
                    <PlayersSelect isUserInfoEntered={setIsUserInfoEntered} player1Symbol={setPlayer1Symbol} player2Symbol={setPlayer2Symbol} isSinglePlayer={true} />
                </div>

                {
                    isUserInfoEntered && (
                        <div className='pb-12'>
                            <SinglePlayerGame player1Name={'You'} player1Symbol={player1Symbol} player2Name={'Computer'} player2Symbol={player2Symbol} />
                        </div>
                    )
                }
            </div>
        </>
    )
}
